--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ekwt/Downloads/163972-space_nasa_logo_japanese-3840x2160.png"

-- Special
background="#101216"
foreground="#e2e0e1"
cursor="#e2e0e1"

-- Colors
color0="#101216"
color1="#D03060"
color2="#F03269"
color3="#C74E72"
color4="#C86E89"
color5="#A1A1A4"
color6="#DEA8B9"
color7="#e2e0e1"
color8="#9e9c9d"
color9="#D03060"
color10="#F03269"
color11="#C74E72"
color12="#C86E89"
color13="#A1A1A4"
color14="#DEA8B9"
color15="#e2e0e1"
