# Shell variables
# Generated by 'wal'
wallpaper='/home/ekwt/Downloads/163972-space_nasa_logo_japanese-3840x2160.png'

# Special
background='#101216'
foreground='#e2e0e1'
cursor='#e2e0e1'

# Colors
color0='#101216'
color1='#D03060'
color2='#F03269'
color3='#C74E72'
color4='#C86E89'
color5='#A1A1A4'
color6='#DEA8B9'
color7='#e2e0e1'
color8='#9e9c9d'
color9='#D03060'
color10='#F03269'
color11='#C74E72'
color12='#C86E89'
color13='#A1A1A4'
color14='#DEA8B9'
color15='#e2e0e1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
